services:
  backend:
    build: ./mycodelib-backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - db

  frontend:
    build: ./mycodelib-frontend
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: jm-password
      MYSQL_DATABASE: my_coding_library
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: jm-password
    ports:
      - "8081:80"
